#!/bin/sh

/bin/echo "=== Starting rcS ==="


# 运行所有启动脚本
for i in /etc/init.d/S??* ; do
    [ ! -f "$i" ] && continue
    case "$i" in
        *.sh)
            (trap - INT QUIT TSTP; set start; . $i)
            ;;
        *)
            $i start
            ;;
    esac
done

/bin/echo "=== rcS complete ==="
