#!/bin/sh
#
# S04pwatchdogd - feed Linux watchdog and send PDM MCU heartbeat
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

NAME="S04pwatchdogd"
DAEMON="/usr/bin/pwatchdogd"
PIDFILE="/var/run/pwatchdogd.pid"


log()
{
    echo "[$NAME] $*"
}

running()
{
    [ -r "$PIDFILE" ] || return 1
    pid="$(cat "$PIDFILE" 2>/dev/null)"
    [ -n "$pid" ] || return 1
    kill -0 "$pid" 2>/dev/null
}

start()
{
    [ -x "$DAEMON" ] || {
        log "$DAEMON not found or not executable"
        return 1
    }

    if running; then
        log "already running"
        return 0
    fi

    log "starting: $DAEMON"
    start-stop-daemon -S -q -b -m -p "$PIDFILE" -x "$DAEMON"
}

stop()
{
    if ! running; then
        rm -f "$PIDFILE"
        log "not running"
        return 0
    fi

    log "stopping"
    start-stop-daemon -K -q -p "$PIDFILE" -x "$DAEMON"
    ret=$?
    rm -f "$PIDFILE"
    return $ret
}

status()
{
    if running; then
        echo "pwatchdogd: running pid $(cat "$PIDFILE")"
        return 0
    fi

    echo "pwatchdogd: stopped"
    return 3
}

case "$1" in
    start|"")
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac

exit $?
